scan_filter_chain:
  - name: robot_body_filter
    type: laser_filters/LaserScanAngularBoundsFilter
    params:
      # filtered scan range：270 deg
      lower_angle: -3.14159  # -180 deg
      upper_angle: -1.57080  # -90 deg